"""Storage protocol for the topic evolution system."""

from __future__ import annotations
from typing import List, Optional, Protocol

from models import Topic, Doc, ClusterState


class Storage(Protocol):
    def load_topic(self, topic_id: str) -> Topic: ...
    def save_topic(self, topic: Topic) -> None: ...
    def save_docs(self, topic_id: str, docs: List[Doc]) -> None: ...
    def recent_docs(self, topic_id: str, window_days: int, limit: int) -> List[Doc]: ...
    def mark_seen_hashes(self, topic_id: str, hashes: List[str]) -> None: ...
    def seen(self, topic_id: str) -> set[str]: ...
    def load_cluster_state(self, topic_id: str, cluster_id: str) -> Optional[ClusterState]: ...
    def save_cluster_state(self, topic_id: str, state: ClusterState) -> None: ...
    def delete_cluster_state(self, topic_id: str, cluster_id: str) -> None: ...
    def get_all_cluster_states_for_topic(self, topic_id: str) -> List[ClusterState]: ...